config/routes.rb
    get 'organizations/sign_up/success', to: 'organizations/registrations#success'
  end

  devise_scope :user do
    patch '/user/confirmation', to: 'users/confirmations#update', as: :update_user_confirmation
    get '/user/registrations/check_username', to: 'users/registrations#check_username'
    get 'users/sign_up/success', to: 'users/registrations#success'
    get 'users/registrations/delete_form', to: 'users/registrations#delete_form'
    delete 'users/registrations', to: 'users/registrations#delete'
    get :finish_signup, to: 'users/registrations#finish_signup'
    patch :do_finish_signup, to: 'users/registrations#do_finish_signup'
  end

  root 'welcome#index'
  get '/welcome', to: 'welcome#welcome'
  get '/cuentasegura', to: 'welcome#verification', as: :cuentasegura

  resources :debates do
    member do
      post :vote
      put :flag
      put :unflag
      put :mark_featured
      put :unmark_featured
    end
    collection do
      get :map
      get :suggest
    end
  end

  resources :proposals do
    member do
      post :vote
      post :vote_featured
      put :flag
      put :unflag
      get :retire_form
      patch :retire
    end
    collection do
      get :map
      get :suggest
      get :summary
    end
  end

  resources :comments, only: [:create, :show], shallow: true do
    member do
      post :vote
      put :flag
      put :unflag
    end
  end

  resources :budgets, only: [:show, :index] do
    resources :groups, controller: "budgets/groups", only: [:show]
    resources :investments, controller: "budgets/investments", only: [:index, :new, :create, :show, :destroy] do
      member { post :vote }
    end
    resource :ballot, only: :show, controller: "budgets/ballots" do
      resources :lines, controller: "budgets/ballot/lines", only: [:create, :destroy]
    end
  end

  scope '/participatory_budget' do
    resources :spending_proposals, only: [:index, :new, :create, :show, :destroy], path: 'investment_projects' do
      post :vote, on: :member
    end
  end

  resources :stats, only: [:index]

  resources :legislations, only: [:show]

  resources :annotations do
    get :search, on: :collection
  end

  resources :polls, only: [:show, :index] do
    resources :questions, only: [:show], controller: 'polls/questions', shallow: true do
      post :answer, on: :member
    end
  end

  resources :users, only: [:show] do
    resources :direct_messages, only: [:new, :create, :show]
  end

  resource :account, controller: "account", only: [:show, :update, :delete] do
    get :erase, on: :collection
  end

  resources :notifications, only: [:index, :show] do
    put :mark_all_as_read, on: :collection
  end

  resources :proposal_notifications, only: [:new, :create, :show]

  resource :verification, controller: "verification", only: [:show]

  scope module: :verification do
    resource :residence, controller: "residence", only: [:new, :create]
    resource :sms, controller: "sms", only: [:new, :create, :edit, :update]
    resource :verified_user, controller: "verified_user", only: [:show]
    resource :email, controller: "email", only: [:new, :show, :create]
    resource :letter, controller: "letter", only: [:new, :create, :show, :edit, :update]
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :organizations, only: :index do
      get :search, on: :collection
      member do
        put :verify
        put :reject
      end
    end

    resources :users, only: [:index, :show] do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :debates, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :proposals, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :spending_proposals, only: [:index, :show, :edit, :update] do
      member do
        patch :assign_admin
        patch :assign_valuators
      end

      get :summary, on: :collection
    end

    resources :budgets do
      resources :budget_groups do
        resources :budget_headings do
        end
      end

      resources :budget_investments, only: [:index, :show, :edit, :update] do
        member { patch :toggle_selection }
      end
    end

    resources :signature_sheets, only: [:index, :new, :create, :show]

    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { get :search}
    end

    resources :comments, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :tags, only: [:index, :create, :update, :destroy]
    resources :officials, only: [:index, :edit, :update, :destroy] do
      get :search, on: :collection
    end

    resources :settings, only: [:index, :update]
    resources :moderators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :valuators, only: [:index, :create] do
      get :search, on: :collection
      get :summary, on: :collection
    end

    resources :managers, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    scope module: :poll do
      resources :polls do
        get :search_questions, on: :member
        patch :add_question, on: :member
        patch :remove_question, on: :member

        resources :booth_assignments, only: [:index, :show, :create, :destroy] do
          get :search_booths, on: :collection
        end

        resources :officer_assignments, only: [:index, :create, :destroy] do
          get :search_officers, on: :collection
          get :by_officer, on: :collection
        end

        resources :recounts, only: :index
        resources :results, only: :index
      end

      resources :officers do
        get :search, on: :collection
      end

      resources :booths
      resources :questions
    end

    resources :verifications, controller: :verifications, only: :index do
      get :search, on: :collection
    end

    resource :activity, controller: :activity, only: :show
    resource :stats, only: :show do
      get :proposal_notifications, on: :collection
      get :direct_messages, on: :collection
    end

    namespace :api do
      resource :stats, only: :show
    end

    resources :geozones, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :site_customization do
      resources :pages, except: [:show]
      resources :images, only: [:index, :update, :destroy]
      resources :content_blocks, except: [:show]
    end
  end

  namespace :moderation do
    root to: "dashboard#index"

    resources :users, only: :index do
      member do
        put :hide
        put :hide_in_moderation_screen
      end
    end

    resources :debates, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :proposals, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :comments, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end
  end

  namespace :valuation do
    root to: "budgets#index"

    resources :spending_proposals, only: [:index, :show, :edit] do
      patch :valuate, on: :member
    end

    resources :budgets, only: :index do
      resources :budget_investments, only: [:index, :show, :edit] do
        patch :valuate, on: :member
      end
    end
  end

  namespace :management do
    root to: "dashboard#index"

    resources :document_verifications, only: [:index, :new, :create] do
      post :check, on: :collection
    end

    resources :email_verifications, only: [:new, :create]

    resources :user_invites, only: [:new, :create]

    resources :users, only: [:new, :create] do
      collection do
        delete :logout
        delete :erase
      end
    end

    resource :account, controller: "account", only: [:show]

    get 'sign_in', to: 'sessions#create', as: :sign_in

    resource :session, only: [:create, :destroy]
    resources :proposals, only: [:index, :new, :create, :show] do
      post :vote, on: :member
      get :print, on: :collection
    end

    resources :spending_proposals, only: [:index, :new, :create, :show] do
      post :vote, on: :member
      get :print, on: :collection
    end

    resources :budgets, only: :index do
      collection do
        get :create_investments
        get :support_investments
        get :print_investments
      end
      resources :investments, only: [:index, :new, :create, :show, :destroy], controller: 'budgets/investments' do
        post :vote, on: :member
        get :print, on: :collection
      end
    end
  end

  namespace :officing do
    resources :polls, only: [:index] do
      get :final, on: :collection

      resources :recounts, only: [:new, :create]
      resources :final_recounts, only: [:new, :create]
      resources :results, only: [:new, :create, :index]
    end
    resource :residence, controller: "residence", only: [:new, :create]
    resources :voters, only: [:new, :create]
    root to: "dashboard#index"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount Tolk::Engine => '/translate', :as => 'tolk'

  # more info pages
  get 'more-information',                     to: 'pages#show', id: 'more_info/index',                as: 'more_info'
  get 'more-information/how-to-use',          to: 'pages#show', id: 'more_info/how_to_use/index',     as: 'how_to_use'
  get 'more-information/faq',                 to: 'pages#show', id: 'more_info/faq/index',            as: 'faq'
  get 'more-information/participation/facts', to: 'pages#show', id: 'more_info/participation/facts',  as: 'participation_facts'
  get 'more-information/participation/world', to: 'pages#show', id: 'more_info/participation/world',  as: 'participation_world'

  # static pages
  get '/blog' => redirect("http://blog.consul/")

app/controllers/custom/debates_controller.rb
class DebatesController < ApplicationController
  include FeatureFlags
  include CommentableActions
  include FlagActions

  before_action :parse_tag_filter, only: :index
  before_action :authenticate_user!, except: [:index, :show, :map]

  feature_flag :debates

  invisible_captcha only: [:create, :update], honeypot: :subtitle

  has_orders %w{created_at confidence_score most_commented featured relevance}, only: :index
  has_orders %w{most_voted newest oldest}, only: :show

  load_and_authorize_resource
  helper_method :resource_model, :resource_name
  respond_to :html, :js

  def index_customization
    @featured_debates = @debates.featured
    @proposal_successfull_exists = Proposal.successful.exists?
  end

  def show
    super
    redirect_to debate_path(@debate), status: :moved_permanently if request.path != debate_path(@debate)
  end
  
  def mark_featured
    @debate.update_attribute(:featured_at, Time.current)
  end

  def unmark_featured
    @debate.update_attribute(:featured_at, nil)
  end
  
  def vote
    @debate.register_vote(current_user, params[:value])
    set_debate_votes(@debate)
    if (@debate.likes - @debate.dislikes) >= Setting['votes_for_debate_success'].to_i
      mark_featured
    end
  end

  private

    def debate_params
      params.require(:debate).permit(:title, :description, :tag_list, :terms_of_service)
    end

    def resource_model
      Debate
    end
end

app/controllers/custom/proposals_controller.rb
class ProposalsController < ApplicationController
  include CommentableActions
  include FlagActions

  before_action :parse_search_terms, only: [:index, :suggest]
  before_action :parse_advanced_search_terms, only: :index
  before_action :parse_tag_filter, only: :index
  before_action :set_search_order, only: :index
  before_action :load_categories, only: [:index, :new, :edit, :map, :summary]
  before_action :load_geozones, only: [:edit, :map, :summary]
  before_action :authenticate_user!, except: [:index, :show, :map, :summary]

  invisible_captcha only: [:create, :update], honeypot: :subtitle

  has_orders %w{created_at confidence_score most_commented relevance archival_date}, only: :index
  has_orders %w{most_voted newest oldest}, only: :show

  load_and_authorize_resource
  helper_method :resource_model, :resource_name
  respond_to :html, :js

  def show
    super
    @notifications = @proposal.notifications
    redirect_to proposal_path(@proposal), status: :moved_permanently if request.path != proposal_path(@proposal)
  end

  def index_customization
    discard_archived
    load_retired
    load_successful_proposals
    load_featured unless @proposal_successful_exists
  end

  def vote
    @proposal.register_vote(current_user, 'yes')
    set_proposal_votes(@proposal)
  end

  def retire
    if valid_retired_params? && @proposal.update(retired_params.merge(retired_at: Time.current))
      redirect_to proposal_path(@proposal), notice: t('proposals.notice.retired')
    else
      render action: :retire_form
    end
  end

  def retire_form
  end

  def vote_featured
    @proposal.register_vote(current_user, 'yes')
    set_featured_proposal_votes(@proposal)
  end

  def summary
    @proposals = Proposal.for_summary
    @tag_cloud = tag_cloud
  end

  private

    def proposal_params
      params.require(:proposal).permit(:title, :question, :summary, :description, :external_url, :video_url, :responsible_name, :tag_list, :terms_of_service, :geozone_id)
    end

    def retired_params
      params.require(:proposal).permit(:retired_reason, :retired_explanation)
    end

    def valid_retired_params?
      @proposal.errors.add(:retired_reason, I18n.t('errors.messages.blank')) if params[:proposal][:retired_reason].blank?
      @proposal.errors.add(:retired_explanation, I18n.t('errors.messages.blank')) if params[:proposal][:retired_explanation].blank?
      @proposal.errors.empty?
    end

    def resource_model
      Proposal
    end

    def set_featured_proposal_votes(proposals)
      @featured_proposals_votes = current_user ? current_user.proposal_votes(proposals) : {}
    end

    def discard_archived
      @resources = @resources.not_archived unless @current_order == "archival_date"
    end

    def load_retired
      if params[:retired].present?
        @resources = @resources.retired
        @resources = @resources.where(retired_reason: params[:retired]) if Proposal::RETIRE_OPTIONS.include?(params[:retired])
      else
        @resources = @resources.not_retired
      end
    end

    def load_featured
      @featured_proposals = Proposal.not_archived.last_week.sort_by_created_at.limit(3) if (!@advanced_search_terms && @search_terms.blank? && @tag_filter.blank? && params[:retired].blank?)
      if @featured_proposals.present?
        set_featured_proposal_votes(@featured_proposals)
        @resources = @resources.where('proposals.id NOT IN (?)', @featured_proposals.map(&:id))
      end
    end

    def load_successful_proposals
      @proposal_successful_exists = Proposal.successful.exists?
    end

end

app/controllers/custom/spending_proposals_controller.rb
class SpendingProposalsController < ApplicationController
  include FeatureFlags

  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { flash.now[:notice] = flash[:notice].html_safe if flash[:html_safe] && flash[:notice] }

  load_and_authorize_resource

  feature_flag :spending_proposals

  invisible_captcha only: [:create, :update], honeypot: :subtitle
  
  has_orders %w{created_at}, only: :index

  respond_to :html, :js

  def index
    @spending_proposals = apply_filters_and_search(SpendingProposal).page(params[:page]).for_render
    set_spending_proposal_votes(@spending_proposals)
  end

  def new
    if user_signed_in? && (current_user.administrator? || current_user.poll_officer?)
      @spending_proposal = SpendingProposal.new
    else
      redirect_to "/"
    end
  end

  def show
    set_spending_proposal_votes(@spending_proposal)
  end

  def create
    @spending_proposal = SpendingProposal.new(spending_proposal_params)
    @spending_proposal.author = current_user

    if @spending_proposal.save
      notice = t('flash.actions.create.spending_proposal', activity: "<a href='#{user_path(current_user, filter: :spending_proposals)}'>#{t('layouts.header.my_activity_link')}</a>")
      redirect_to @spending_proposal, notice: notice, flash: { html_safe: true }
    else
      render :new
    end
  end

  def destroy
    spending_proposal = SpendingProposal.find(params[:id])
    spending_proposal.destroy
    redirect_to user_path(current_user, filter: 'spending_proposals'), notice: t('flash.actions.destroy.spending_proposal')
  end

  def vote
    @spending_proposal.register_vote(current_user, 'yes')
    set_spending_proposal_votes(@spending_proposal)
  end

  private

    def spending_proposal_params
      params.require(:spending_proposal).permit(:title, :description, :external_url, :geozone_id, :association_name, :terms_of_service)
    end

    def set_geozone_name
      if params[:geozone] == 'all'
        @geozone_name = t('geozones.none')
      else
        @geozone_name = Geozone.find(params[:geozone]).name
      end
    end

    def apply_filters_and_search(target)
      target = target.all.sort_by_created_at
      if params[:association_name].present?
        target = target.by_association_name(params[:association_name])
        @association_name = params[:association_name]
      end
      
      if params[:geozone].present?
        target = target.by_geozone(params[:geozone])
        set_geozone_name
      end
      target = target.search(params[:search]) if params[:search].present?
      target
    end
end

app/views/custom/shared/_admin_login_items.html.erb
<% if current_user %>

  <% if current_user.administrator? %>
    <li>
      <%= link_to admin_root_path do %>
        <%= image_tag(image_path_for('icon_administration.png'), class: "show-for-small-only") %>
        <%= t("layouts.header.administration") %>
      <% end %>
    </li>
  <% end %>

  <% if current_user.administrator? || current_user.moderator? %>
    <li>
      <%= link_to moderation_root_path do %>
        <%= image_tag(image_path_for('icon_moderation.png'), class: "show-for-small-only") %>
        <%= t("layouts.header.moderation") %>
      <% end %>
    </li>
  <% end %>

  <% if feature?(:spending_proposals) && (current_user.administrator? || current_user.valuator?) %>
    <li>
      <%= link_to valuation_root_path do %>
        <%= image_tag(image_path_for('icon_valuation.png'), class: "show-for-small-only") %>
        <%= t("layouts.header.valuation") %>
      <% end %>
    </li>
  <% end %>

  <% if current_user.administrator? || current_user.manager? %>
    <li>
      <%= link_to management_sign_in_path do %>
        <%= image_tag(image_path_for('icon_management.png'), class: "show-for-small-only") %>
        <%= t("layouts.header.management") %>
      <% end %>
    </li>
  <% end %>

  <% if current_user.administrator? || current_user.poll_officer? %>
    <li>
      <%= link_to t("layouts.header.officing"), officing_root_path, class: "hide-for-small-only" %>
      <%= link_to officing_root_path, class: "show-for-small-only" do %>
        <%= image_tag(image_path_for('icon_officing.png')) %>
        <%= t("layouts.header.officing_light") %>
      <% end %>
    </li>
  <% end %>
  
<% end %>

app/views/custom/shared/_advanced_search.html.erb
<div class="relative">
  <%= link_to t("shared.advanced_search.title"), "#advanced_search_form", id: 'js-advanced-search-title', class: "advanced-search small" %>
</div>

<div class="row advanced-search-form">
  <%= form_tag search_path, id: "advanced_search_form", method: :get do %>
    <div id='js-advanced-search' data-advanced-search-terms=<%= @advanced_search_terms.present? %> style="display: none">

      <div class="small-12 large-6 column">
        <label for="search">
          <%= t("shared.advanced_search.general") %>
        </label>
        <%= text_field_tag "search", params[:search],
                           placeholder: t("shared.advanced_search.keywords") %>
      </div>

      <div class="small-12 large-6 column">
        <div class="small-12 large-12">
          <label for="js-advanced-search-date-min"><%= t("shared.advanced_search.date") %></label>
          <%= select_tag('advanced_search[date_min]', date_range_options,
                        include_blank: t("shared.advanced_search.date_range_blank"),
                        id: 'js-advanced-search-date-min') %>
        </div>

        <div id='js-custom-date' class='small-12 large-12 column' style="display: none">
          <div class="row">
            <div class='small-12 large-6 column'>
              <label for="advanced_search_date_min">
                <%= t("shared.advanced_search.from") %> (<%= t("shared.advanced_search.date_placeholder") %>)
              </label>
              <%= text_field_tag 'advanced_search[date_min]',
                                  params[:advanced_search].try(:[], :date_min),
                                  class: 'js-calendar' %>
            </div>
            <div class='small-12 large-6 column'>
              <label for="advanced_search_date_max">
                <%= t("shared.advanced_search.to") %> (<%= t("shared.advanced_search.date_placeholder") %>)
              </label>
              <%= text_field_tag 'advanced_search[date_max]',
                                  params[:advanced_search].try(:[], :date_max),
                                  class: 'js-calendar' %>
            </div>
          </div>
        </div>
      </div>

      <div class="small-12 medium-3 column end clear">
        <%= submit_tag t("shared.advanced_search.search"), class: 'button expanded' %>
      </div>

    </div>
  <% end %>
</div>

app/views/custom/shared/_analyticstracking.html.erb
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '', 'auto');
      ga('send', 'pageview');
    </script>

app/views/custom/shared/_news_author_info.html.erb
<% if resource.author.hidden? || resource.author.erased? %>
  <span class="icon-deleted author-deleted"></span>
  <span class="author deleted">
    <%= t("shared.author_info.author_deleted") %>
  </span>
<% else %>
  <%= avatar_image(resource.author, seed: resource.author_id, size: 32, class: 'author-photo') %>
  <span class="author">
    <%= link_to resource.author.name, user_path(resource.author) %>
  </span>

  <% if resource.author.display_official_position_badge? %>
    &nbsp;&bull;&nbsp;
    <span class="label round level-<%= resource.author.official_level %>">
      <%= resource.author.official_position %>
    </span>
  <% end %>
<% end %>

<% if resource.author.verified_organization? %>
  &nbsp;&bull;&nbsp;
  <span class="label round is-association">
    <%= t("shared.collective") %>
  </span>
<% end %>

app/views/custom/shared/_subnavigation.html.erb
<div class="small-12 medium-9 column">
  <ul>
    <li>
      <%= layout_menu_link_to t("layouts.header.debates"), debates_path, controller_name == 'debates', accesskey: "1" %>
    </li>
    
    <li>
      <%= layout_menu_link_to t("layouts.header.proposals"), proposals_path, controller_name == 'proposals', accesskey: "2" %>
    </li>
    
    <% if feature?(:polls) %>
      <li>
        <%= layout_menu_link_to t("layouts.header.poll_questions"), polls_path, controller_name == "polls", accesskey: "3" %>
      </li>
    <% end %>
    
    <% if feature?(:spending_proposals) %>
      <li>
        <%= layout_menu_link_to t("layouts.header.spending_proposals"), spending_proposals_path, controller_name == 'spending_proposals', accesskey: "5" %>
      </li>
    <% end %>
    
    <li>
      <%= link_to t("layouts.header.more_info"), more_info_path, accesskey: "5", class: ("active" if current_page?(more_info_path)) %>
    </li>
  </ul>
</div>

app/views/custom/shared/_subnavigation_light.html.erb
<% if feature?(:debates) %>
  <li>
    <%= link_to debates_path, accesskey: "1", class: ("active" if current_page?(debates_path)) do %>
      <%= image_tag(image_path_for('icon_debates.png')) %>
      <%= t("layouts.header.debates") %>
    <% end %>
  </li>
<% end %>

<li>
  <%= link_to proposals_path, accesskey: "2", class: ("active" if current_page?(proposals_path)) do %>
    <%= image_tag(image_path_for('icon_proposals.png')) %>
    <%= t("layouts.header.proposals") %>
  <% end %>
</li>

<% if feature?(:polls) %>
  <li>
    <%= link_to polls_path, accesskey: "3", class: ("active" if current_page?(polls_path)) do %>
      <%= image_tag(image_path_for('icon_polls.png')) %>
      <%= t("layouts.header.poll_questions") %>
    <% end %>
  </li>
<% end %>

<% if feature?(:spending_proposals) %>
  <li>
    <%= link_to spending_proposals_path, accesskey: "5", class: ("active" if current_page?(spending_proposals_path)) do %>
      <%= image_tag(image_path_for('icon_news.png')) %>
      <%= t("layouts.header.spending_proposals") %>
    <% end %>
  </li>
<% end %>

<li>
  <%= link_to more_info_path, accesskey: "4", class: ("active" if current_page?(more_info_path)) do %>
    <%= image_tag(image_path_for('icon_more_info.png')) %>
    <%= t("layouts.header.more_info_light") %>
  <% end %>
</li>

app/views/custom/shared/_tag_cloud.html.erb
<div class="sidebar-divider"></div>
<div id="tag-cloud">
  <h2 class="sidebar-title"><%= t("shared.tags_cloud.tags") %></h2>
  <br>
  <ul class="no-bullet tag-cloud tags">
    <% @tag_cloud.tags.each do |tag| %>
      <li class="inline-block">
        <%= link_to tag.name, taggables_path(taggable, tag.name), class: taggable %>
      </li>
    <% end %>
  </ul>
</div>

app/views/custom/shared/_top_links.html.erb
<ul class="no-bullet external-links">
  <li>
    <%= link_to t("layouts.header.external_link_aude"),
                t("layouts.header.external_link_aude_url"),
                target: "_blank",
                title: t("layouts.header.external_link_aude_url") %>
  </li>

  <%= raw content_block("top_links", I18n.locale) %>
</ul>

app/views/custom/shared/_top_links_light.html.erb
<li>
  <%= link_to t("layouts.header.external_link_aude_url"), target: "_blank", title: t("layouts.header.external_link_aude_url") do %>
    <%= image_tag(image_path_for('icon_aude.png')) %>
    <%= t("layouts.header.external_link_aude") %>
  <% end %>
</li>

<%= raw content_block("top_links", I18n.locale) %>